language: java
jdk:
- oraclejdk8
sudo: false

cache:
  directories:
  - $HOME/.gradle

install:
  - bash ./.travis/installdeps.sh
  - git clone https://github.com/m-language/m-jvm ../m-jvm

script:
  - bash ./.travis/build.sh 